services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A your_project_name worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
