# Generated by Django 5.1.3 on 2024-11-22 15:32

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_expires'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user', 'duration', 'start_date')},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration in days'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 23, 15, 32, 16, 831059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 16, 2, 16, 829853, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_frame',
        ),
    ]
